package ca.hccis.files.entity;

import ca.hccis.files.bo.GameBO;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

public class GameBOTest {
    /**
     * Test the calculation for a game where the home team should win. Created following TDD.
     * @since 20261002
     * @author BML
     */
    @Test
    void testDetermineWinner_Home() {
        // Innings in the game.
        ArrayList<Inning> innings = new ArrayList<>();
        innings.add(new Inning(1, 3, 0));
        innings.add(new Inning(2, 1, 3));
        innings.add(new Inning(3, 2, 1));
        innings.add(new Inning(4, 0, 1));
        innings.add(new Inning(5, 2, 2));
        innings.add(new Inning(6, 3, 2));
        innings.add(new Inning(7, 1, 2));

        // This game would be a home win (12-11).

        String actual = GameBO.determineWinner(innings, "Apples", "Oranges");
        assertEquals("Apples", actual);
    }

    /**
     * Test the calculation for a game where the road team should win. Created following TDD.
     * @since 20261002
     * @author BML
     */
    @Test
    void testDetermineWinner_Road() {
        ArrayList<Inning> innings = new ArrayList<>();
        innings.add(new Inning(1, 3, 2));
        innings.add(new Inning(2, 1, 3));
        innings.add(new Inning(3, 2, 1));
        innings.add(new Inning(4, 0, 1));
        innings.add(new Inning(5, 2, 2));
        innings.add(new Inning(6, 3, 2));
        innings.add(new Inning(7, 1, 2));

        // This game would be a road win (12-13)

        String actual = GameBO.determineWinner(innings, "Apples", "Oranges");
        assertEquals("Oranges", actual);
    }

    /**
     * Test the calculation for a game where the score should be tied after 7 innings. Created following TDD.
     * @since 20261002
     * @author BML
     */
    @Test
    void testDetermineWinner_Tie() {
        ArrayList<Inning> innings = new ArrayList<>();
        innings.add(new Inning(1, 3, 1));
        innings.add(new Inning(2, 1, 3));
        innings.add(new Inning(3, 2, 1));
        innings.add(new Inning(4, 0, 1));
        innings.add(new Inning(5, 2, 2));
        innings.add(new Inning(6, 3, 2));
        innings.add(new Inning(7, 1, 2));

        // This game would be a tie (12-12)

        String actual = GameBO.determineWinner(innings, "Apples", "Oranges");
        assertEquals("", actual);
    }

    // The following methods were generated by Google's AI Mode.

    private final String HOME = "Thunder";
    private final String ROAD = "Lightning";

    /**
     * Helper method to map raw score arrays to Inning objects.
     * Maps to: new Inning(inningNum, homeRuns, roadRuns)
     */
    private ArrayList<Inning> createMockInnings(int[][] scores) {
        ArrayList<Inning> innings = new ArrayList<>();
        for (int i = 0; i < scores.length; i++) {
            int inningNum = i + 1;
            int homeRuns = scores[i][0];
            int roadRuns = scores[i][1];
            innings.add(new Inning(inningNum, homeRuns, roadRuns));
        }
        return innings;
    }

    @Test
    @DisplayName("Home team wins with a run majority after a regulation 7-inning game")
    void testHomeTeamWinsStandardGame() {
        int[][] scores = {
                {2, 1}, {0, 3}, {4, 0}, {1, 1}, {3, 0}, {0, 2}, {2, 0}
        }; // Home: 12 runs, Road: 7 runs
        ArrayList<Inning> innings = createMockInnings(scores);

        String winner = GameBO.determineWinner(innings, HOME, ROAD);

        // Assert Type 1: Verify exact value match
        assertEquals(HOME, winner, "The home team should be declared the winner.");
        // Assert Type 2: Confirm the opponent was not incorrectly returned
        assertNotEquals(ROAD, winner, "The road team should not be returned on a home team victory.");
    }

    @Test
    @DisplayName("Road team wins with a run majority after a regulation 7-inning game")
    void testRoadTeamWinsStandardGame() {
        int[][] scores = {
                {0, 3}, {2, 2}, {1, 4}, {3, 0}, {0, 2}, {4, 1}, {1, 2}
        }; // Home: 11 runs, Road: 14 runs
        ArrayList<Inning> innings = createMockInnings(scores);

        String winner = GameBO.determineWinner(innings, HOME, ROAD);

        // Assert Type 1: Verify exact value match
        assertEquals(ROAD, winner, "The road team should be declared the winner.");
        // Assert Type 2: Confirm the opponent was not incorrectly returned
        assertNotEquals(HOME, winner, "The home team should not be returned on a road team victory.");
    }

    @Test
    @DisplayName("Game ends in a tie after 7 innings, returning an empty string")
    void testGameEndsInTie() {
        int[][] scores = {
                {2, 2}, {1, 1}, {3, 3}, {0, 0}, {2, 2}, {1, 1}, {0, 0}
        }; // Home: 11 runs, Road: 11 runs
        ArrayList<Inning> innings = createMockInnings(scores);

        String winner = GameBO.determineWinner(innings, HOME, ROAD);

        // Assert Type 1: Verify exact value match
        assertEquals("", winner, "A tie game should return an empty string.");
        // Assert Type 2: Confirm it did not return actual team names
        assertNotEquals(HOME, winner, "A tie game should not declare the home team as the winner.");
        assertNotEquals(ROAD, winner, "A tie game should not declare the road team as the winner.");
    }

    @Test
    @DisplayName("Minimum short game (5 innings) works correctly")
    void testMinimumInningsGame() {
        int[][] scores = {
                {3, 0}, {4, 1}, {2, 0}, {5, 2}, {1, 0}
        }; // Home: 15 runs, Road: 3 runs
        ArrayList<Inning> innings = createMockInnings(scores);

        String winner = GameBO.determineWinner(innings, HOME, ROAD);

        // Assert Type 1
        assertEquals(HOME, winner, "Should correctly calculate a winner for a shortened 5-inning game.");
        // Assert Type 2
        assertNotEquals("", winner, "A short game with a clear run margin should not result in a tie.");
    }

    @Test
    @DisplayName("Extended softball game (extra innings) works correctly")
    void testExtraInningsGame() {
        int[][] scores = {
                {2, 2}, {1, 1}, {0, 0}, {3, 3}, {1, 1}, {0, 0}, {2, 2}, // Tied 11-11 after 7 innings
                {1, 3} // 8th inning (Road scores 3, Home scores 1)
        }; // Home: 12 runs, Road: 14 runs
        ArrayList<Inning> innings = createMockInnings(scores);

        String winner = GameBO.determineWinner(innings, HOME, ROAD);

        // Assert Type 1
        assertEquals(ROAD, winner, "Should correctly aggregate runs across extra innings.");
        // Assert Type 2
        assertNotEquals("", winner, "Extra inning run gaps should resolve any prior ties.");
    }
}
